# conf/config.yaml
# 默认为True, 控制台打印消息
debug: true

# 日志保留天数
log_days: 3

# 指定进程数
process_num: 3
jd_puzzle_process_num: 1
# 宠汪汪进程数
joy_process_num: 1
JOY_PROCESS_NUM: 1
jd_cookies:
  - pt_key=AAJhVE1cADCshNAezreaRI0Q6jieELdeSUTxesxusB6czD5i3TYRt1k8mdllfrzLDsxULVlEEdA;pt_pin=zzz_ys;;
  - pt_key=AAJhVFXcADAh5Wd9NPggNM-8IoEeP9QaeNIlL3Hr52-5rpcyVHRL9wA32VDD1TQCmLOjffq4SCE;pt_pin=jd_66393a9de8e2f;;
  - pt_key=AAJhVFQ8ADBQo3AnTqNJg1rleS24ftcan-IcbentNlIxcdllBTAzlIqJYIUV2KDIar0DDGzwbBE;pt_pin=37866223_m;;
# 东东农场是否使用水滴换豆卡, 100水滴换20京豆
jd_farm_bean_card: false

# 东东农场每天保留多少水滴, 用于明天的十次浇水任务
jd_farm_retain_water: 80

# 消息通知
notify:
  # TG机器人Token
  tg_bot_token: aaa
  # TG用户ID
  tg_user_id: bbb
  push_plus_token: null

  # push+ group 一对多推送才需要次配置
  push_plus_group: null

  # 依次填上corpid的值,corpsecret的值,touser的值,agentid,media_id的值，注意用,号隔开。
  qywx_am: weixin

# 在此列表中的脚本, 将不会加入到定时任务中, 如需立即生效, 请手动执行命令: docker-entrypoint
crontab_exclude_scripts:
  #- jd_bean_indiana.py
