name: jd_travel_shop_task

on:
    workflow_dispatch:
    schedule:
        - cron: "25 18 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_travel_shop_task

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: 'Set up Python'
            uses: actions/setup-python@v1
            with:
              python-version: 3.7

          - name: 'Install requirements'
            run: pip install -r ./requirements.txt
            
                  
          - name: run
            run: |             
             sed -i "s/default=0/default=1/g" ./db/model.py
             mkdir conf 
             mv ./config.yaml ./conf/config.yaml
             python3 jd_travels.py
             python3 jd_travel_shop_task.py                       
